version: '3.7'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    volumes:
      - /home/ec2-user/config:/config
      - /home/ec2-user/movies:/data/movies
      - /home/ec2-user/tv:/data/tv
